version: '3.4'

services:
  catalog-service:
    build:
      context: .
      dockerfile: ./apps/catalog-service/docker/build-app/Dockerfile
    environment:
      - EVENT_BUS_CONNECTION=amqp://rabbitmq:5672
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - catalog-db-migrate

  postgres:
    container_name: postgres
    image: denlysenko/postgres-multi
    env_file: .env
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERS=${PG_CATALOG_USER}:${PG_CATALOG_PASSWORD}
      - POSTGRES_DATABASES=${PG_CATALOG_DB}:${PG_CATALOG_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - '15672:15672'
      - '5672:5672'

  catalog-db-migrate:
    build:
      context: .
      dockerfile: ./apps/catalog-service/docker/run-migrations/Dockerfile
    env_file: .env
    command:
      [
        './wait-for-it/wait-for-it.sh',
        'postgres:5432',
        '--',
        '/bin/bash',
        '-c',
        'typeorm migration:run --config ./orm-docker.config.js',
      ]
    depends_on:
      - postgres

volumes:
  postgres_data:
    external: false
