replicaCount: 1

image:
  repository: denlysenko/eshop-ordering-service-api
  pullPolicy: IfNotPresent
  tag: v1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "ordering-service"

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
  hosts:
    - host: e-shop-ordering-service.local
      paths:
        - path: /swagger/v1
          pathType: ImplementationSpecific
        - path: /api/v1/orders/.*
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  secret: e-shop-secret
  values:
    - name: EVENT_BUS_CONNECTION
      value: "amqp://rabbitmq:5672"
    - name: EXCHANGE
      value: "e-shop-on-containers:dev"
    - name: KEYCLOAK_FRONTEND_HOST
      value: "sso.e-shop.local"

livenessProbe:
  enabled: true
  path: /health
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 60
  timeoutSeconds: 20
  failureThreshold: 1
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /health
  port: 3000
  timeoutSeconds: 3
  initialDelaySeconds: 10
  periodSeconds: 5
  failureThreshold: 2
  successThreshold: 1