replicaCount: 1

image:
  repository: denlysenko/postgres-multi
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "postgres"

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5432
  loadBalancer:
    enabled: true
    name: "postgres-loadbalancer"

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  secret: e-shop-secret
  values:
    - name: POSTGRES_USERS
      value: $(PG_CATALOG_USER):$(PG_CATALOG_PASSWORD)|$(PG_ORDERING_USER):$(PG_ORDERING_PASSWORD)|$(PG_IDENTITY_USER):$(PG_IDENTITY_PASSWORD)|$(PG_MARKETING_USER):$(PG_MARKETING_PASSWORD)|$(PG_WEBHOOKS_USER):$(PG_WEBHOOKS_PASSWORD)|$(PG_BASKET_USER):$(PG_BASKET_PASSWORD)
    - name: POSTGRES_DATABASES
      value: $(PG_CATALOG_DB):$(PG_CATALOG_USER)|$(PG_ORDERING_DB):$(PG_ORDERING_USER)|$(PG_IDENTITY_DB):$(PG_IDENTITY_USER)|$(PG_MARKETING_DB):$(PG_MARKETING_USER)|$(PG_WEBHOOKS_DB):$(PG_WEBHOOKS_USER)|$(PG_BASKET_DB):$(PG_BASKET_USER)

persistence:
  enabled: true

  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  existingClaim: postgres-claim

  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteMany
  size: 200Mi
  mountPath: /var/lib/postgresql/data
  volumeName: postgres-data

livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 3
  periodSeconds: 5