apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity-service.fullname" . }}
  labels:
    {{- include "identity-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.statsPort }}
      targetPort: {{ .Values.service.statsPort }}
      protocol: TCP
      name: stats
  selector:
    {{- include "identity-service.selectorLabels" . | nindent 4 }}
