apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "basket-service.fullname" . }}-dbmigrate
  labels:
    {{- include "basket-service.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  completions: 1
  template:
    metadata:
      labels:
        {{- include "basket-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: "groundnuty/k8s-wait-for:1.3"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - "pod"
          - "-lapp.kubernetes.io/name=postgres"
      containers:
        - name: {{ .Chart.Name }}-db-migrations
          image: "{{ .Values.image.repository | replace "api" "db-migrations" }}:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [
            './wait-for-it/wait-for-it.sh',
            'postgres:5432',
            '--',
            '/bin/bash',
            '-c',
            'typeorm migration:run --config ./orm-docker.config.js',
          ]
          envFrom:
          - secretRef:
              name: {{ .Values.env.secret }}